//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicTemplate3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasicTemplate3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BarObjectHierarchy.
        /// </summary>
        public static string BarObjectHierarchyId {
            get {
                return ResourceManager.GetString("BarObjectHierarchyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BarObjectTree.
        /// </summary>
        public static string BarObjectTreeName {
            get {
                return ResourceManager.GetString("BarObjectTreeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Block.
        /// </summary>
        public static string ButtonText {
            get {
                return ResourceManager.GetString("ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CreateBlock {
            get {
                object obj = ResourceManager.GetObject("CreateBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;customUI xmlns=&quot;http://schemas.spaceclaim.com/customui&quot;&gt;
        ///  &lt;panel command=&quot;BasicTemplate3.FooTool&quot; label=&quot;Tool&quot; modeLabel=&quot;TextBox&quot;&gt;
        ///    &lt;group id=&quot;BasicTemplate3.FooTool&quot; label=&quot;Textbox Options&quot; optionsType=&quot;primary&quot;&gt;
        ///      &lt;container id=&quot;BasicTemplate3.FooToolContainer&quot; layoutOrientation=&quot;vertical&quot;&gt;
        ///        &lt;checkBox id=&quot;BasicTemplate3.CheckBox&quot; label=&quot;Unitless&quot; command=&quot;BasicTemplate3.CheckBox&quot;/&gt;
        ///        &lt;textBox id=&quot;BasicTemplate3.TextBoxDouble&quot; command=&quot;Ba [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FooToolOptions {
            get {
                return ResourceManager.GetString("FooToolOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap OK_32px {
            get {
                object obj = ResourceManager.GetObject("OK_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;customUI
        ///  xmlns=&quot;http://schemas.spaceclaim.com/customui&quot;
        ///  xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///  xsi:schemaLocation=&quot;http://schemas.spaceclaim.com/customui http://schemas.spaceclaim.com/customui/SpaceClaimCustomUI.V20.xsd&quot;&gt;
        ///
        ///	&lt;ribbon&gt;
        ///		&lt;tabs&gt;
        ///			&lt;tab id=&quot;Discovery BasicTemplate3&quot; command=&quot;BasicTemplate3.RibbonTab&quot;&gt;
        ///				&lt;group id =&quot;Geometry&quot; command=&quot;BasicTemplate3.Geometry&quot; label=&quot;Geometry&quot;&gt;
        ///					&lt;button id=&quot;BasicTemplate3.CreateBlock&quot; si [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Ribbon {
            get {
                return ResourceManager.GetString("Ribbon", resourceCulture);
            }
        }
    }
}
