//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicTemplate3.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasicTemplate3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BarObjectHierarchy ähnelt.
        /// </summary>
        public static string BarObjectHierarchyId {
            get {
                return ResourceManager.GetString("BarObjectHierarchyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BarObjectTree ähnelt.
        /// </summary>
        public static string BarObjectTreeName {
            get {
                return ResourceManager.GetString("BarObjectTreeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;customUI xmlns=&quot;http://schemas.spaceclaim.com/customui&quot;&gt;
        ///  &lt;panel command=&quot;BasicTemplate3.BarTool&quot; label=&quot;Tool&quot; modeLabel=&quot;TextBox&quot;&gt;
        ///    &lt;group id=&quot;BasicTemplate3.BarToolGuide&quot; label=&quot;Tool Guides&quot; optionsType=&quot;toolGuide&quot;&gt;
        ///      &lt;button id=&quot;BasicTemplate3.TickMark&quot; command=&quot;BasicTemplate3.TickMark&quot;/&gt;
        ///    &lt;/group&gt;
        ///    &lt;group id=&quot;BasicTemplate3.BarTool&quot; label=&quot;Textbox Options&quot; optionsType=&quot;primary&quot;&gt;
        ///      &lt;container id=&quot;BasicTemplate3.BarToolContainer&quot; layoutOrie [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string BarToolOptions {
            get {
                return ResourceManager.GetString("BarToolOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap button1 {
            get {
                object obj = ResourceManager.GetObject("button1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap button2 {
            get {
                object obj = ResourceManager.GetObject("button2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Block ähnelt.
        /// </summary>
        public static string ButtonText {
            get {
                return ResourceManager.GetString("ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CreateBlock {
            get {
                object obj = ResourceManager.GetObject("CreateBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;customUI xmlns=&quot;http://schemas.spaceclaim.com/customui&quot;&gt;
        ///  &lt;panel command=&quot;BasicTemplate3.FooTool&quot; label=&quot;Tool&quot; modeLabel=&quot;TextBox&quot;&gt;
        ///    &lt;group id=&quot;BasicTemplate3.FooTool&quot; label=&quot;Textbox Options&quot; optionsType=&quot;primary&quot;&gt;
        ///      &lt;container id=&quot;BasicTemplate3.FooToolContainer&quot; layoutOrientation=&quot;vertical&quot;&gt;
        ///        &lt;checkBox id=&quot;BasicTemplate3.CheckBox&quot; label=&quot;Unitless&quot; command=&quot;BasicTemplate3.CheckBox&quot;/&gt;
        ///        &lt;textBox id=&quot;BasicTemplate3.TextBoxDouble&quot; command=&quot;Ba [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string FooToolOptions {
            get {
                return ResourceManager.GetString("FooToolOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap OK_32px {
            get {
                object obj = ResourceManager.GetObject("OK_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;customUI
        ///  xmlns=&quot;http://schemas.spaceclaim.com/customui&quot;
        ///  xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///  xsi:schemaLocation=&quot;http://schemas.spaceclaim.com/customui http://schemas.spaceclaim.com/customui/SpaceClaimCustomUI.V20.xsd&quot;&gt;
        ///
        ///  &lt;ribbon&gt;
        ///    &lt;tabs&gt;
        ///      &lt;tab id=&quot;Discovery BasicTemplate3&quot; command=&quot;BasicTemplate3.RibbonTab&quot;&gt;
        ///        &lt;group id =&quot;Geometry&quot; command=&quot;BasicTemplate3.Geometry&quot; label=&quot;Geometry&quot;&gt;
        ///          &lt;button id=&quot;BasicTemplate3. [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string Ribbon {
            get {
                return ResourceManager.GetString("Ribbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;customUI xmlns=&quot;http://schemas.spaceclaim.com/customui&quot;&gt;
        ///    &lt;panel command=&quot;BasicTemplate3.SimulationTool&quot; label=&quot;Tool&quot; modeLabel=&quot;TextBoxMaybe&quot;&gt;
        ///        &lt;group id=&quot;BasicTemplate3.SimulationToolGuide&quot; label=&quot;Tool Guides&quot; optionsType=&quot;toolGuide&quot;&gt;
        ///            &lt;button id=&quot;BasicTemplate3.AcceptOrder&quot; command=&quot;BasicTemplate3.AcceptOrder&quot;/&gt;
        ///        &lt;/group&gt;
        ///        &lt;group id=&quot;BasicTemplate3.SimulationTool&quot; label=&quot;Textbox Options&quot; optionsType=&quot;primary&quot;&gt;
        ///             [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string SimToolOptions {
            get {
                return ResourceManager.GetString("SimToolOptions", resourceCulture);
            }
        }
    }
}
